version: '3.7'
services:
  vmq:
    image: vernemq/vernemq
    container_name: verne
    restart: unless_stopped
    ports:
      - '1883':'1883'
      - '8883':'8883'
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: '0.0.0.0:1883'